server:
  port: 8081
  shutdown: GRACEFUL

spring:
  application:
    name: money-maker

logging:
  level:
    root: INFO
    money.maker: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%logger{simple}] - %msg%n"

websocket:
  configuration:
    uri: ws://localhost:8082
    reconnect-timeout: 3000

bar:
  time-frame: 30

scheduler:
  connect-auto: true
  task-cron: "0 * * * * ?"

dev:
  enable: true
  websocket:
    server:
      port: 8082
