server:
  port: 8081
  shutdown: GRACEFUL

spring:
  application:
    name: money-maker

logging:
  level:
    root: INFO
    money.maker: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%logger{simple}] - %msg%n"

websocket:
  configuration:
    uri: ws://localhost:8082
    reconnect-timeout: 1000

bar:
  time-frame: 30

scheduler:
  connect-auto: false
  close-cron: "0 0 16 * * MON-FRI"
  open-cron: "0 0 9 * * MON-FRI"
  task-cron: "0 * * * * MON-FRI"
  pool-size: 5
