server:
  port: ${port:8080}
  shutdown: GRACEFUL

spring:
  application:
    name: broker-integrator
  data:
    redis:
      host: ${redis-host:localhost}
      port: ${redis-port:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,loggers,info
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true

logging:
  level:
    root: INFO
    data.aggregator: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%logger{simple}] - %msg%n"

broker:
  kite:
    api-key: ENC(nrsjscTL+Im0KidtdH3Q5IjS/lsr0/leAwKc/5O91PJj/Cktn6X3/A==)
    api-secret: ENC(frPi7mtUvvZPCTAP2OP8A/Qoo8ihr8QZNWorKJqQsOxBACCOhDo8kYduOLnpBnFKVja1eWd+RhU=)


