logging:
  level:
    strategy.engine: DEBUG
    strategy.engine.indicator: TRACE
    strategy.engine.rule: TRACE

management:
  endpoints:
    web:
      exposure:
        include: mappings

bar:
  time-frame: 60
