server:
  port: ${port:8084}
  shutdown: GRACEFUL

spring:
  application:
    name: strategy-engine
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,loggers,info
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true

logging:
  level:
    root: INFO
    execution.engine: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%logger{simple}] - %msg%n"

bar:
  time-frame: 60
