name: Build Broker Integrator
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - broker-integrator/**


permissions:
  actions: write
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      service: broker-integrator
      port: 8080
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}