name: Build Execution Engine
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - execution-engine/**

permissions:
  actions: write
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      service: execution-engine
      port: 8083