name: Build Data Emitter
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - data-emitter/**

permissions:
  actions: write
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      service: data-emitter
      port: 8082
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}